
os:
  - linux

language: php

php:
  - '7.2'

before_script:
  - cp .env.travis .env
  - composer update
  - php artisan cache:clear --no-interaction
  - php artisan config:clear --no-interaction
  - php artisan key:generate --no-interaction


branches:
  only:
    - production